# Generated by Django 5.2.9 on 2025-12-29 18:45

import apps.users.models
import core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('field_officer', 'Field Officer'), ('hq_analyst', 'HQ Analyst')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_picture_upload_to)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('subcounty', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('ki', 'Kikuyu'), ('lu', 'Luhya'), ('ka', 'Kamba')], default='en', max_length=2)),
                ('receive_sms_notifications', models.BooleanField(default=True)),
                ('receive_push_notifications', models.BooleanField(default=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=255)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Size in hectares', max_digits=10)),
                ('primary_crop', models.CharField(max_length=100)),
                ('secondary_crops', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[core.validators.validate_latitude])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[core.validators.validate_longitude])),
                ('years_of_experience', models.IntegerField(default=0)),
                ('farming_type', models.CharField(choices=[('subsistence', 'Subsistence'), ('commercial', 'Commercial'), ('mixed', 'Mixed')], default='subsistence', max_length=50)),
                ('has_irrigation', models.BooleanField(default=False)),
                ('has_greenhouse', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farmer profile',
                'verbose_name_plural': 'farmer profiles',
                'db_table': 'farmer_profiles',
            },
        ),
        migrations.CreateModel(
            name='FieldOfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('assigned_counties', models.JSONField(default=list)),
                ('assigned_subcounties', models.JSONField(default=list)),
                ('coverage_area_radius', models.IntegerField(default=50, help_text='Radius in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_officers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'field officer profile',
                'verbose_name_plural': 'field officer profiles',
                'db_table': 'field_officer_profiles',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alert', 'Weather Alert'), ('advisory', 'Advisory'), ('message', 'Message'), ('system', 'System'), ('community', 'Community')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('sent_via_push', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
